- name: Add Node GPG apt Key
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    state: present

- name: Add node Repository
  apt_repository:
    repo: "deb [arch=amd64] https://deb.nodesource.com/node_{{ node_version }}.x {{ ansible_distribution_release }} main"
    state: present

- name: Update apt-get repo and cache
  apt:
    update_cache: true
    cache_valid_time: 86400

- name: Update apt and install nodejs
  package:
    state: present
    name:
      - nodejs
      - npm

- name: Install global packages
  npm:
    name: "{{ item }}"
    state: present
    global: true
  with_items:
    - yarn
    - zx
