env:
  browser: true
  es2021: true
  node: true

extends:
  - standard-with-typescript
  - airbnb-typescript
  - plugin:import/recommended
  - plugin:jsx-a11y/recommended
  - plugin:react/recommended

parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: ./tsconfig.json

settings:
  react:
    version: detect

  'import/parsers':
    { '@typescript-eslint/parser': ['.ts', '.tsx', '.woff2', '.png'] }

  import/resolver:
    {
      'typescript': { 'project': ['apps/backend/tsconfig.json'] },
      'node':
        {
          'extensions': ['.js', '.jsx', '.ts', '.tsx'],
          'moduleDirectory': ['src/'],
        },
    }

ignorePatterns:
  - config/*.js
  - dist/*
  - prettier.config.js

plugins:
  - react
  - react-hooks

rules:
  max-len: ['error', 120]
  quotes: ['error', 'single']
  import/no-default-export: 2
  import/no-extraneous-dependencies: 0
  multiline-ternary: 0
  generator-star-spacing: off
  no-console: ['error', { 'allow': ['warn', 'info', 'error'] }]
  no-void: ['off']
  import/order:
    [
      'error',
      {
        'groups': ['builtin', 'external', 'type', 'parent', 'sibling', 'index'],
      },
    ]
  react/react-in-jsx-scope: off
  react-hooks/rules-of-hooks: 'error'
  react-hooks/exhaustive-deps: off
  '@typescript-eslint/no-throw-literal': off
  '@typescript-eslint/no-unnecessary-type-assertion': off
  '@typescript-eslint/no-import-type-side-effects': 'error'
  '@typescript-eslint/ban-types': off
  '@typescript-eslint/no-invalid-void-type': off
  '@typescript-eslint/no-non-null-assertion': off
  '@typescript-eslint/restrict-template-expressions': off
  '@typescript-eslint/explicit-function-return-type': off
  '@typescript-eslint/strict-boolean-expressions': off
  '@typescript-eslint/indent': off
  '@typescript-eslint/consistent-type-definitions': ['error', 'type']
  '@typescript-eslint/member-delimiter-style':
    [
      'error',
      {
        'multiline': { 'delimiter': 'semi', 'requireLast': true },
        'singleline': { 'delimiter': 'semi', 'requireLast': false },
        'multilineDetection': 'brackets',
      },
    ]
  '@typescript-eslint/consistent-type-assertions':
    [
      'error',
      { 'assertionStyle': 'as', 'objectLiteralTypeAssertions': 'allow' },
    ]
  '@typescript-eslint/naming-convention':
    [
      'error',
      {
        'selector': 'variable',
        'modifiers': ['destructured'],
        'format': null,
        'custom': { 'regex': '^_$', 'match': false },
      },
    ]
  '@typescript-eslint/no-unused-vars':
    [
      'error',
      {
        'argsIgnorePattern': '^_$',
        'varsIgnorePattern': '^_$',
        'caughtErrorsIgnorePattern': '^_$',
      },
    ]
