node_version: 19

all_groups:
  - name: webusers
  - name: deployusers
  - name: docker

all_users:
  - name: ci
    groups: webusers,deployusers,docker

  - name: deploy
    groups: deployusers,webusers,wheel,docker

  - name: web
    groups: webusers

local_paths:
  ssh_keys:
    authorized: "{{ playbook_dir }}/../keys/ssh/authorized"

remote_paths:
  www: /www

podman:
  volumes_path: "{{ remote_paths.www }}/volumes"
