node_version: 20

all_groups:
  - name: wheel

all_users:
  - name: deploy
    groups:

  - name: admin
    groups: wheel

local_paths:
  keys_dir: '{{ playbook_dir | dirname }}/keys'
  ssh_keys:
    authorized: "{{ playbook_dir | dirname }}/keys/authorized"

podman:
  volumes_path: /containers/volumes
  registry:
    credentials: "{{ lookup('file', '{{ playbook_dir | dirname }}/keys/podman/registry-credentials.json') | from_json }}"
